[2022-11-10T18:11:30.235+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: a_third_dag.create_table manual__2022-11-10T18:07:27.343422+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-11-10T18:11:30.244+0000] {local_task_job.py:103} INFO - Task is not able to be run
[2022-11-10T18:12:22.567+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_third_dag.create_table manual__2022-11-10T18:07:27.343422+00:00 [queued]>
[2022-11-10T18:12:22.584+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_third_dag.create_table manual__2022-11-10T18:07:27.343422+00:00 [queued]>
[2022-11-10T18:12:22.586+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-10T18:12:22.587+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 4
[2022-11-10T18:12:22.589+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-10T18:12:22.623+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-10 18:07:27.343422+00:00
[2022-11-10T18:12:22.633+0000] {standard_task_runner.py:55} INFO - Started process 10634 to run task
[2022-11-10T18:12:22.647+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_third_dag', 'create_table', 'manual__2022-11-10T18:07:27.343422+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/third_dug.py', '--cfg-path', '/tmp/tmps8dhgs56']
[2022-11-10T18:12:22.649+0000] {standard_task_runner.py:83} INFO - Job 51: Subtask create_table
[2022-11-10T18:12:22.762+0000] {task_command.py:376} INFO - Running <TaskInstance: a_third_dag.create_table manual__2022-11-10T18:07:27.343422+00:00 [running]> on host 0b03955da713
[2022-11-10T18:12:22.888+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_third_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T18:07:27.343422+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-10T18:07:27.343422+00:00
[2022-11-10T18:12:22.902+0000] {base.py:71} INFO - Using connection ID '***' for task execution.
[2022-11-10T18:12:22.915+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS curr_pair (
            price NUMERIC NOT NULL,
            pair VARCHAR NOT NULL
            );
          , parameters: None
[2022-11-10T18:12:23.008+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=a_third_dag, task_id=create_table, execution_date=20221110T180727, start_date=20221110T181222, end_date=20221110T181223
[2022-11-10T18:12:23.058+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-10T18:12:23.100+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
