[2022-11-30T17:18:21.602+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: clean_trash_bucket.clean_bucket manual__2022-11-30T14:00:21.617373+00:00 [None]>
[2022-11-30T17:18:21.612+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: clean_trash_bucket.clean_bucket manual__2022-11-30T14:00:21.617373+00:00 [None]>
[2022-11-30T17:18:21.616+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T17:18:21.618+0000] {taskinstance.py:1363} INFO - Starting attempt 36 of 36
[2022-11-30T17:18:21.621+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T17:18:21.635+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): clean_bucket> on 2022-11-30 14:00:21.617373+00:00
[2022-11-30T17:18:21.642+0000] {standard_task_runner.py:55} INFO - Started process 3025 to run task
[2022-11-30T17:18:21.646+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'clean_trash_bucket', 'clean_bucket', 'manual__2022-11-30T14:00:21.617373+00:00', '--job-id', '209', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/CleanTrashBucket.py', '--cfg-path', '/tmp/tmpif4vl35l']
[2022-11-30T17:18:21.649+0000] {standard_task_runner.py:83} INFO - Job 209: Subtask clean_bucket
[2022-11-30T17:18:21.714+0000] {task_command.py:376} INFO - Running <TaskInstance: clean_trash_bucket.clean_bucket manual__2022-11-30T14:00:21.617373+00:00 [running]> on host 31b8349c3542
[2022-11-30T17:18:21.769+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***.golovanov@gmail.com
AIRFLOW_CTX_DAG_OWNER=Eugeny Golovanov
AIRFLOW_CTX_DAG_ID=clean_trash_bucket
AIRFLOW_CTX_TASK_ID=clean_bucket
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T14:00:21.617373+00:00
AIRFLOW_CTX_TRY_NUMBER=36
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T14:00:21.617373+00:00
[2022-11-30T17:18:21.786+0000] {base.py:71} INFO - Using connection ID 'Postgres' for task execution.
[2022-11-30T17:18:21.796+0000] {logging_mixin.py:120} INFO - Oops! Something went wrong.
[2022-11-30T17:18:21.798+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-30T17:18:21.809+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=clean_trash_bucket, task_id=clean_bucket, execution_date=20221130T140021, start_date=20221130T171821, end_date=20221130T171821
[2022-11-30T17:18:21.860+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-30T17:18:21.877+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
